Add unit tests
fond-of/spryker-company-unit-addresses-rest-api pull request #1
Opened 2020-03-12 08:28 UTC by SpiderDan98

- Add unit tests

2020-03-16 09:51 UTC, SpiderDan98 commented on composer.json
> +    "spryker/glue-application": "^1.0.0"
Checked for possible versions

2020-04-01 11:56 UTC, daniel-rose requested changes

2020-04-01 11:56 UTC, daniel-rose commented on src/FondOfSpryker/Client/CompanyUnitAddressesRestApi/CompanyUnitAddressesRestApiFactory.php
> +     * @throws
remove @throws

2020-04-01 11:56 UTC, daniel-rose commented on src/FondOfSpryker/Zed/CompanyUnitAddressesRestApi/Business/CompanyUnitAddressesRestApiBusinessFactory.php
> +     * @throws
remove @throws

2020-04-06 07:56 UTC, daniel-rose approved these changes

2020-04-06 07:56 UTC, merged